// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdfoekmbgomedqtjsfpo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkZm9la21iZ29tZWRxdGpzZnBvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4Mjc3MzYsImV4cCI6MjA2MDQwMzczNn0.4oS4m6okeZWT9ETSXbb51sUsn6bBf0OUl1xsa7pEtO4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);